### ISSUE TITLE
Длинные текст композиции вылазит под кноки

### ISSUE THREAD

**Issue by EL-shadow** [Ty3uK/YMC#3]
Скриншот

![изображение](https://user-images.githubusercontent.com/1730762/59086499-94c30d80-890a-11e9-97de-f170f3783894.png)

**Comment by Ty3uK** [comment]
@EL-shadow спасибо, поправлю!

**Comment by Ty3uK** [comment]
@EL-shadow исправлено в версии [1.0.4](https://github.com/Ty3uK/YMC/releases/tag/104-110)
